// Generated by CoffeeScript 1.3.3
var app, assets, engines, express, getMS, http, pages, port, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

http = require('http');

app = express();

app.use(assets());

app.set('view engine', 'jade');

pages = {
  main: {
    url: "/",
    weight: 3
  },
  search: {
    url: "/search?q=test",
    weight: 1
  },
  notFound: {
    url: "/notfound",
    weight: 1
  }
};

engines = {
  google: "https://www.google.com",
  bing: "http://www.bing.com"
};

app.get('/', function(req, res) {
  var output;
  output = getMS('phishvids.com');
  return res.render('index');
});

app.get('/site/:site', function(req, res) {
  return getMS(req.params.site, function(json) {
    return res.send(json);
  });
});

getMS = function(site, callback) {
  var i, output, start, _results,
    _this = this;
  output = [];
  start = 100;
  i = start;
  _results = [];
  while (--i > 0) {
    start = new Date();
    _results.push(http.get({
      host: site,
      port: 80
    }, function(res) {
      var length;
      length = new Date() - start;
      output.push({
        message: "Request took: " + length + ("ms (" + site + ")"),
        time: length,
        site: site,
        status: res.statusCode
      });
      if (output.length >= 99) {
        return callback(output);
      }
    }));
  }
  return _results;
};

port = process.env.PORT || process.env.VMC_APP_PORT || 4000;

app.listen(port, function() {
  return console.log("Listening on " + port);
});
